name: australian-labradoodle
favicon: null
layout_spectrum: 0.8667407603934407
typography_spectrum: 0.15909606777131557
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5975265011657029
  lightness: 0.30991772026754916
  saturation: 0.7696831184439361
  rhythmicContrast: 0.20973750832490623
purpose: []
